# Install

In [ ]:
# !pip uninstall -y numpy scipy -> gensim 및 BART와의 버전 충돌 이슈로 직접 버전 설정해줌
!pip install pandas==1.5.3 numpy==1.23.5 scipy==1.10.1 --force-reinstall

Collecting pandas==1.5.3
  Downloading pandas-1.5.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting numpy==1.23.5
  Downloading numpy-1.23.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.3 kB)
Collecting scipy==1.10.1
  Downloading scipy-1.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.9/58.9 kB 2.0 MB/s eta 0:00:00
Collecting python-dateutil>=2.8.1 (from pandas==1.5.3)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas==1.5.3)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.1->pandas==1.5.3)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Downloading pandas-1.5.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 105.1 MB/s eta 0:00:00
Downloading numpy-1.23.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 115.9 MB/s eta 0:00:00
Downloading scipy-1.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.1/34.1 MB 67.4 MB/s eta 0:00:00
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 22.1 MB/s eta 0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 509.2/509.2 kB 42.2 MB/s eta 0:00:00
Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: pytz, six, numpy, scipy, python-dateutil, pandas
  Attempting uninstall: pytz
    Found existing installation: pytz 2025.2
    Uninstalling pytz-2025.2:
      Successfully uninstalled pytz-2025.2
  Attempting uninstall: six
    Found existing installation: six 1.17.0
    Uninstalling six-1.17.0:
      Successfully uninstalled six-1.17.0
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.9.0.post0
    Uninstalling python-dateutil-2.9.0.post0:
      Successfully uninstalled python-dateutil-2.9.0.post0
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 1.5.3 which is incompatible.
dask-cudf-cu12 25.2.2 requires pandas<2.2.4dev0,>=2.0, but you have pandas 1.5.3 which is incompatible.
jaxlib 0.5.1 requires numpy>=1.25, but you have numpy 1.23.5 which is incompatible.
jaxlib 0.5.1 requires scipy>=1.11.1, but you have scipy 1.10.1 which is incompatible.
albumentations 2.0.8 requires numpy>=1.24.4, but you have numpy 1.23.5 which is incompatible.
xarray 2025.3.1 requires numpy>=1.24, but you have numpy 1.23.5 which is incompatible.
xarray 2025.3.1 requires pandas>=2.1, but you have pandas 1.5.3 which is incompatible.
cvxpy 1.6.6 requires scipy>=1.11.0, but you have scipy 1.10.1 which is incompatible.
mizani 0.13.5 requires pandas>=2.2.0, but you have pandas 1.5.3 which is incompatible.
jax 0.5.2 requires numpy>=1.25, but you have numpy 1.23.5 which is incompatible.
jax 0.5.2 requires scipy>=1.11.1, but you have scipy 1.10.1 which is incompatible.
cudf-cu12 25.2.1 requires pandas<2.2.4dev0,>=2.0, but you have pandas 1.5.3 which is incompatible.
chex 0.1.89 requires numpy>=1.24.1, but you have numpy 1.23.5 which is incompatible.
blosc2 3.5.0 requires numpy>=1.26, but you have numpy 1.23.5 which is incompatible.
bigframes 2.8.0 requires numpy>=1.24.0, but you have numpy 1.23.5 which is incompatible.
treescope 0.1.9 requires numpy>=1.25.2, but you have numpy 1.23.5 which is incompatible.
db-dtypes 1.4.3 requires numpy>=1.24.0, but you have numpy 1.23.5 which is incompatible.
scikit-image 0.25.2 requires numpy>=1.24, but you have numpy 1.23.5 which is incompatible.
scikit-image 0.25.2 requires scipy>=1.11.4, but you have scipy 1.10.1 which is incompatible.
tsfresh 0.21.0 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.10.1 which is incompatible.
plotnine 0.14.5 requires pandas>=2.2.0, but you have pandas 1.5.3 which is incompatible.
pymc 5.23.0 requires numpy>=1.25.0, but you have numpy 1.23.5 which is incompatible.
albucore 0.0.24 requires numpy>=1.24.4, but you have numpy 1.23.5 which is incompatible.
imbalanced-learn 0.13.0 requires numpy<3,>=1.24.3, but you have numpy 1.23.5 which is incompatible.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 1.23.5 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.23.5 which is incompatible.
dask-expr 1.1.21 requires pandas>=2, but you have pandas 1.5.3 which is incompatible.
xarray-einstats 0.9.1 requires numpy>=1.25, but you have numpy 1.23.5 which is incompatible.
xarray-einstats 0.9.1 requires scipy>=1.11, but you have scipy 1.10.1 which is incompatible.
Successfully installed numpy-1.23.5 pandas-1.5.3 python-dateutil-2.9.0.post0 pytz-2025.2 scipy-1.10.1 six-1.17.0

In [ ]:
!pip install tensorflow==2.12.0 --force-reinstall

Collecting tensorflow==2.12.0
  Downloading tensorflow-2.12.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Collecting absl-py>=1.0.0 (from tensorflow==2.12.0)
  Downloading absl_py-2.3.0-py3-none-any.whl.metadata (2.4 kB)
Collecting astunparse>=1.6.0 (from tensorflow==2.12.0)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=2.0 (from tensorflow==2.12.0)
  Downloading flatbuffers-25.2.10-py2.py3-none-any.whl.metadata (875 bytes)
Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.12.0)
  Downloading gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
Collecting google-pasta>=0.1.1 (from tensorflow==2.12.0)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow==2.12.0)
  Downloading grpcio-1.73.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting h5py>=2.9.0 (from tensorflow==2.12.0)
  Downloading h5py-3.14.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.7 kB)
Collecting jax>=0.3.15 (from tensorflow==2.12.0)
  Downloading jax-0.6.2-py3-none-any.whl.metadata (13 kB)
Collecting keras<2.13,>=2.12.0 (from tensorflow==2.12.0)
  Downloading keras-2.12.0-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting libclang>=13.0.0 (from tensorflow==2.12.0)
  Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
Collecting numpy<1.24,>=1.22 (from tensorflow==2.12.0)
  Using cached numpy-1.23.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.3 kB)
Collecting opt-einsum>=2.3.2 (from tensorflow==2.12.0)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Collecting packaging (from tensorflow==2.12.0)
  Downloading packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 (from tensorflow==2.12.0)
  Downloading protobuf-4.25.8-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)
Collecting setuptools (from tensorflow==2.12.0)
  Downloading setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Collecting six>=1.12.0 (from tensorflow==2.12.0)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting tensorboard<2.13,>=2.12 (from tensorflow==2.12.0)
  Downloading tensorboard-2.12.3-py3-none-any.whl.metadata (1.8 kB)
Collecting tensorflow-estimator<2.13,>=2.12.0 (from tensorflow==2.12.0)
  Downloading tensorflow_estimator-2.12.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting termcolor>=1.1.0 (from tensorflow==2.12.0)
  Downloading termcolor-3.1.0-py3-none-any.whl.metadata (6.4 kB)
Collecting typing-extensions>=3.6.6 (from tensorflow==2.12.0)
  Downloading typing_extensions-4.14.0-py3-none-any.whl.metadata (3.0 kB)
Collecting wrapt<1.15,>=1.11.0 (from tensorflow==2.12.0)
  Downloading wrapt-1.14.1-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.12.0)
  Downloading tensorflow_io_gcs_filesystem-0.37.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow==2.12.0)
  Downloading wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Collecting jaxlib<=0.6.2,>=0.6.2 (from jax>=0.3.15->tensorflow==2.12.0)
  Downloading jaxlib-0.6.2-cp311-cp311-manylinux2014_x86_64.whl.metadata (1.3 kB)
Collecting ml_dtypes>=0.5.0 (from jax>=0.3.15->tensorflow==2.12.0)
  Downloading ml_dtypes-0.5.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (21 kB)
INFO: pip is looking at multiple versions of jax to determine which version is compatible with other requirements. This could take a while.
Collecting jax>=0.3.15 (from tensorflow==2.12.0)
  Downloading jax-0.6.1-py3-none-any.whl.metadata (13 kB)
Collecting jaxlib<=0.6.1,>=0.6.1 (from jax>=0.3.15->tensorflow==2.12.0)
  Downloading jaxlib-0.6.1-cp311-cp311-manylinux2014_x86_64.whl.metadata (1.2 kB)
Collecting jax>=0.3.15 (from tensorflow==2.12.0)
  Downloading jax-0.6.0-py3-none-any.whl.metadata (22 kB)
Collecting jaxlib<=0.6.0,>=0.6.0 (from jax>=0.3.15->tensorflow==2.12.0)
  Downloading jaxlib-0.6.0-cp311-cp311-manylinux2014_x86_64.whl.metadata (1.2 kB)
Collecting jax>=0.3.15 (from tensorflow==2.12.0)
  Downloading jax-0.5.3-py3-none-any.whl.metadata (22 kB)
Collecting jaxlib<=0.5.3,>=0.5.3 (from jax>=0.3.15->tensorflow==2.12.0)
  Downloading jaxlib-0.5.3-cp311-cp311-manylinux2014_x86_64.whl.metadata (1.2 kB)
Collecting jax>=0.3.15 (from tensorflow==2.12.0)
  Downloading jax-0.5.2-py3-none-any.whl.metadata (22 kB)
Collecting jaxlib<=0.5.2,>=0.5.1 (from jax>=0.3.15->tensorflow==2.12.0)
  Downloading jaxlib-0.5.1-cp311-cp311-manylinux2014_x86_64.whl.metadata (978 bytes)
Collecting jax>=0.3.15 (from tensorflow==2.12.0)
  Downloading jax-0.5.1-py3-none-any.whl.metadata (22 kB)
  Downloading jax-0.5.0-py3-none-any.whl.metadata (22 kB)
Collecting jaxlib<=0.5.0,>=0.5.0 (from jax>=0.3.15->tensorflow==2.12.0)
  Downloading jaxlib-0.5.0-cp311-cp311-manylinux2014_x86_64.whl.metadata (978 bytes)
Collecting jax>=0.3.15 (from tensorflow==2.12.0)
  Downloading jax-0.4.38-py3-none-any.whl.metadata (22 kB)
Collecting jaxlib<=0.4.38,>=0.4.38 (from jax>=0.3.15->tensorflow==2.12.0)
  Downloading jaxlib-0.4.38-cp311-cp311-manylinux2014_x86_64.whl.metadata (1.0 kB)
INFO: pip is still looking at multiple versions of jax to determine which version is compatible with other requirements. This could take a while.
Collecting jax>=0.3.15 (from tensorflow==2.12.0)
  Downloading jax-0.4.37-py3-none-any.whl.metadata (22 kB)
Collecting jaxlib<=0.4.37,>=0.4.36 (from jax>=0.3.15->tensorflow==2.12.0)
  Downloading jaxlib-0.4.36-cp311-cp311-manylinux2014_x86_64.whl.metadata (1.0 kB)
Collecting jax>=0.3.15 (from tensorflow==2.12.0)
  Downloading jax-0.4.36-py3-none-any.whl.metadata (22 kB)
  Downloading jax-0.4.35-py3-none-any.whl.metadata (22 kB)
Collecting jaxlib<=0.4.35,>=0.4.34 (from jax>=0.3.15->tensorflow==2.12.0)
  Downloading jaxlib-0.4.35-cp311-cp311-manylinux2014_x86_64.whl.metadata (983 bytes)
Collecting jax>=0.3.15 (from tensorflow==2.12.0)
  Downloading jax-0.4.34-py3-none-any.whl.metadata (22 kB)
Collecting jaxlib<=0.4.34,>=0.4.34 (from jax>=0.3.15->tensorflow==2.12.0)
  Downloading jaxlib-0.4.34-cp311-cp311-manylinux2014_x86_64.whl.metadata (983 bytes)
Collecting jax>=0.3.15 (from tensorflow==2.12.0)
  Downloading jax-0.4.33-py3-none-any.whl.metadata (22 kB)
Collecting jaxlib<=0.4.33,>=0.4.33 (from jax>=0.3.15->tensorflow==2.12.0)
  Downloading jaxlib-0.4.33-cp311-cp311-manylinux2014_x86_64.whl.metadata (983 bytes)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
Collecting jax>=0.3.15 (from tensorflow==2.12.0)
  Downloading jax-0.4.31-py3-none-any.whl.metadata (22 kB)
Collecting jaxlib<=0.4.31,>=0.4.30 (from jax>=0.3.15->tensorflow==2.12.0)
  Downloading jaxlib-0.4.31-cp311-cp311-manylinux2014_x86_64.whl.metadata (983 bytes)
Collecting jax>=0.3.15 (from tensorflow==2.12.0)
  Downloading jax-0.4.30-py3-none-any.whl.metadata (22 kB)
Collecting jaxlib<=0.4.30,>=0.4.27 (from jax>=0.3.15->tensorflow==2.12.0)
  Downloading jaxlib-0.4.30-cp311-cp311-manylinux2014_x86_64.whl.metadata (1.0 kB)
Collecting scipy>=1.9 (from jax>=0.3.15->tensorflow==2.12.0)
  Downloading scipy-1.16.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.9/61.9 kB 2.8 MB/s eta 0:00:00
Collecting google-auth<3,>=1.6.3 (from tensorboard<2.13,>=2.12->tensorflow==2.12.0)
  Downloading google_auth-2.40.3-py2.py3-none-any.whl.metadata (6.2 kB)
Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.13,>=2.12->tensorflow==2.12.0)
  Downloading google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting markdown>=2.6.8 (from tensorboard<2.13,>=2.12->tensorflow==2.12.0)
  Downloading markdown-3.8.2-py3-none-any.whl.metadata (5.1 kB)
Collecting requests<3,>=2.21.0 (from tensorboard<2.13,>=2.12->tensorflow==2.12.0)
  Downloading requests-2.32.4-py3-none-any.whl.metadata (4.9 kB)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.13,>=2.12->tensorflow==2.12.0)
  Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard<2.13,>=2.12->tensorflow==2.12.0)
  Downloading werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
Collecting cachetools<6.0,>=2.0.0 (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow==2.12.0)
  Downloading cachetools-5.5.2-py3-none-any.whl.metadata (5.4 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow==2.12.0)
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting rsa<5,>=3.1.4 (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow==2.12.0)
  Downloading rsa-4.9.1-py3-none-any.whl.metadata (5.6 kB)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow==2.12.0)
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Collecting charset_normalizer<4,>=2 (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow==2.12.0)
  Downloading charset_normalizer-3.4.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (35 kB)
Collecting idna<4,>=2.5 (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow==2.12.0)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow==2.12.0)
  Downloading urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow==2.12.0)
  Downloading certifi-2025.6.15-py3-none-any.whl.metadata (2.4 kB)
INFO: pip is looking at multiple versions of scipy to determine which version is compatible with other requirements. This could take a while.
Collecting scipy>=1.9 (from jax>=0.3.15->tensorflow==2.12.0)
  Downloading scipy-1.15.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 6.0 MB/s eta 0:00:00
Collecting MarkupSafe>=2.1.1 (from werkzeug>=1.0.1->tensorboard<2.13,>=2.12->tensorflow==2.12.0)
  Downloading MarkupSafe-3.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Collecting pyasn1<0.7.0,>=0.6.1 (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow==2.12.0)
  Downloading pyasn1-0.6.1-py3-none-any.whl.metadata (8.4 kB)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow==2.12.0)
  Downloading oauthlib-3.3.1-py3-none-any.whl.metadata (7.9 kB)
Downloading tensorflow-2.12.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (586.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 586.0/586.0 MB 1.5 MB/s eta 0:00:00
Downloading absl_py-2.3.0-py3-none-any.whl (135 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.7/135.7 kB 11.9 MB/s eta 0:00:00
Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading flatbuffers-25.2.10-py2.py3-none-any.whl (30 kB)
Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 4.2 MB/s eta 0:00:00
Downloading grpcio-1.73.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 123.6 MB/s eta 0:00:00
Downloading h5py-3.14.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 121.0 MB/s eta 0:00:00
Downloading jax-0.4.30-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 93.3 MB/s eta 0:00:00
Downloading keras-2.12.0-py2.py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 84.1 MB/s eta 0:00:00
Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 96.1 MB/s eta 0:00:00
Using cached numpy-1.23.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
Downloading opt_einsum-3.4.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.9/71.9 kB 7.0 MB/s eta 0:00:00
Downloading protobuf-4.25.8-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 27.8 MB/s eta 0:00:00
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Downloading tensorboard-2.12.3-py3-none-any.whl (5.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 126.5 MB/s eta 0:00:00
Downloading setuptools-80.9.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 73.8 MB/s eta 0:00:00
Downloading tensorflow_estimator-2.12.0-py2.py3-none-any.whl (440 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 kB 35.5 MB/s eta 0:00:00
Downloading tensorflow_io_gcs_filesystem-0.37.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 123.9 MB/s eta 0:00:00
Downloading termcolor-3.1.0-py3-none-any.whl (7.7 kB)
Downloading typing_extensions-4.14.0-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 4.1 MB/s eta 0:00:00
Downloading wrapt-1.14.1-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 8.7 MB/s eta 0:00:00
Downloading packaging-25.0-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 6.9 MB/s eta 0:00:00
Downloading google_auth-2.40.3-py2.py3-none-any.whl (216 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.1/216.1 kB 19.9 MB/s eta 0:00:00
Downloading google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Downloading jaxlib-0.4.30-cp311-cp311-manylinux2014_x86_64.whl (79.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.6/79.6 MB 26.6 MB/s eta 0:00:00
Downloading markdown-3.8.2-py3-none-any.whl (106 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 kB 9.4 MB/s eta 0:00:00
Downloading ml_dtypes-0.5.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 115.1 MB/s eta 0:00:00
Downloading requests-2.32.4-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 6.6 MB/s eta 0:00:00
Downloading scipy-1.15.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.7/37.7 MB 56.4 MB/s eta 0:00:00
Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 117.7 MB/s eta 0:00:00
Downloading werkzeug-3.1.3-py3-none-any.whl (224 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 22.3 MB/s eta 0:00:00
Downloading wheel-0.45.1-py3-none-any.whl (72 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 7.5 MB/s eta 0:00:00
Downloading cachetools-5.5.2-py3-none-any.whl (10 kB)
Downloading certifi-2025.6.15-py3-none-any.whl (157 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.7/157.7 kB 14.9 MB/s eta 0:00:00
Downloading charset_normalizer-3.4.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (147 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.3/147.3 kB 15.0 MB/s eta 0:00:00
Downloading idna-3.10-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 kB 6.5 MB/s eta 0:00:00
Downloading MarkupSafe-3.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23 kB)
Downloading pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.3/181.3 kB 18.8 MB/s eta 0:00:00
Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Downloading rsa-4.9.1-py3-none-any.whl (34 kB)
Downloading urllib3-2.5.0-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.8/129.8 kB 13.4 MB/s eta 0:00:00
Downloading oauthlib-3.3.1-py3-none-any.whl (160 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.1/160.1 kB 16.7 MB/s eta 0:00:00
Downloading pyasn1-0.6.1-py3-none-any.whl (83 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.1/83.1 kB 8.1 MB/s eta 0:00:00
Installing collected packages: libclang, flatbuffers, wrapt, wheel, urllib3, typing-extensions, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, six, setuptools, pyasn1, protobuf, packaging, opt-einsum, oauthlib, numpy, MarkupSafe, markdown, keras, idna, grpcio, gast, charset_normalizer, certifi, cachetools, absl-py, werkzeug, scipy, rsa, requests, pyasn1-modules, ml_dtypes, h5py, google-pasta, astunparse, requests-oauthlib, jaxlib, google-auth, jax, google-auth-oauthlib, tensorboard, tensorflow
  Attempting uninstall: libclang
    Found existing installation: libclang 18.1.1
    Uninstalling libclang-18.1.1:
      Successfully uninstalled libclang-18.1.1
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 25.2.10
    Uninstalling flatbuffers-25.2.10:
      Successfully uninstalled flatbuffers-25.2.10
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.17.2
    Uninstalling wrapt-1.17.2:
      Successfully uninstalled wrapt-1.17.2
  Attempting uninstall: wheel
    Found existing installation: wheel 0.45.1
    Uninstalling wheel-0.45.1:
      Successfully uninstalled wheel-0.45.1
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.4.0
    Uninstalling urllib3-2.4.0:
      Successfully uninstalled urllib3-2.4.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.14.0
    Uninstalling typing_extensions-4.14.0:
      Successfully uninstalled typing_extensions-4.14.0
  Attempting uninstall: termcolor
    Found existing installation: termcolor 3.1.0
    Uninstalling termcolor-3.1.0:
      Successfully uninstalled termcolor-3.1.0
  Attempting uninstall: tensorflow-io-gcs-filesystem
    Found existing installation: tensorflow-io-gcs-filesystem 0.37.1
    Uninstalling tensorflow-io-gcs-filesystem-0.37.1:
      Successfully uninstalled tensorflow-io-gcs-filesystem-0.37.1
  Attempting uninstall: tensorboard-data-server
    Found existing installation: tensorboard-data-server 0.7.2
    Uninstalling tensorboard-data-server-0.7.2:
      Successfully uninstalled tensorboard-data-server-0.7.2
  Attempting uninstall: six
    Found existing installation: six 1.17.0
    Uninstalling six-1.17.0:
      Successfully uninstalled six-1.17.0
  Attempting uninstall: setuptools
    Found existing installation: setuptools 75.2.0
    Uninstalling setuptools-75.2.0:
      Successfully uninstalled setuptools-75.2.0
  Attempting uninstall: pyasn1
    Found existing installation: pyasn1 0.6.1
    Uninstalling pyasn1-0.6.1:
      Successfully uninstalled pyasn1-0.6.1
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.29.5
    Uninstalling protobuf-5.29.5:
      Successfully uninstalled protobuf-5.29.5
  Attempting uninstall: packaging
    Found existing installation: packaging 24.2
    Uninstalling packaging-24.2:
      Successfully uninstalled packaging-24.2
  Attempting uninstall: opt-einsum
    Found existing installation: opt_einsum 3.4.0
    Uninstalling opt_einsum-3.4.0:
      Successfully uninstalled opt_einsum-3.4.0
  Attempting uninstall: oauthlib
    Found existing installation: oauthlib 3.3.1
    Uninstalling oauthlib-3.3.1:
      Successfully uninstalled oauthlib-3.3.1
  Attempting uninstall: numpy

In [ ]:
!pip install summa
!pip install transformers

In [ ]:
# 라이브러리
import pandas as pd
import numpy as np
import pickle
from urllib.request import urlretrieve, urlopen
import gzip
import zipfile
import math
import nltk
import re
from tqdm import tqdm
tqdm.pandas()  # <- 이걸 실행해야 progress_apply가 활성화됨

import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from sklearn.metrics.pairwise import cosine_similarity
import networkx as nx
from summa.summarizer import summarize

nltk.download('punkt_tab')

# 데이터 분할 및 인코더
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_absolute_percentage_error

# 토큰화 및 패딩
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# 시각화 라이브러리
import matplotlib.pyplot as plt

# 성능 평가 라이브러리
from sklearn.metrics import mean_absolute_error, mean_squared_error

print(f'pandas version: {pd.__version__}')
print(f'numpy version: {np.__version__}')
print(f'tensorflow version: {tf.__version__}')       # 2.13.0 등

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

pandas version: 1.5.3
numpy version: 1.23.5
tensorflow version: 2.12.0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Config/Function

In [ ]:
DATA_SAVE_PATH = '/content/drive/MyDrive/박민경_논문1/dataset/prep'
# CATEGORY = 'yelp'
# USER_ID = 'user_id'
# ITEM_ID = 'rest_id'
# REVIEW_COL = 'review_text'
# RATING_COL = 'review_stars'

CATEGORY = 'movie'
USER_ID = 'userID'
ITEM_ID = 'itemID'
RATING_COL = 'rating'
REVIEW_COL = 'reviewtext'

mean_seq_length = 44                   # book = 118, movie = 44, yelp = 113

In [ ]:
# Functions: prep, embedding, summarization with TextRank
## 1) .을 공백으로 처리했을 때 ''인지 확인하는 함수
def clean_text(text):
  cleaned = text.replace('.', '').strip()
  return cleaned == ''


# 2) 리뷰 데이터에 '.', '..' 등의 리뷰인 경우 제거하여 처리
def is_meaningful_sentence_list(sentence_list):
    if not isinstance(sentence_list, list):
        return False
    cleaned = [s.strip() for s in sentence_list if s.strip()]
    return len(cleaned) > 0


# 3) embedding
def embed_review_sentences(review_list, glove_dict, dim=300):
    sentences = [s.strip() for s in review_list if s.strip()]  # 공백 제거 및 비어 있는 문장 제외
    embeddings = []

    for sentence in sentences:
        tokens = word_tokenize(sentence)
        vectors = [glove_dict[token] for token in tokens if token in glove_dict]
        if vectors:
            embedding = np.mean(vectors, axis=0)
        else:
            embedding = np.zeros(dim)
        embeddings.append(embedding)

    return sentences, embeddings

# 4) summarize
def safe_summarize(text, ratio=0.6):
    if len(text.split(' ') ) > 250000:
      text = text[:250000]
    try:
        summary = summarize(text, ratio=ratio)
        return summary if summary and summary.strip() else text
    except Exception:
        return text  # 예외 발생 시 원문 그대로


def summarize_Textrank(df, user_item = 'user', ratio = 0.6):
    df[f'{user_item}_summary'] = df['Reviews_origin'].progress_apply(lambda x: safe_summarize(x, ratio=ratio))
    df[f'{user_item}_summary'] = df[f'{user_item}_summary'].apply(lambda x: x.replace('.\n', '. '))

    return df

In [ ]:
# 텍스트 패딩을 생성한 후, 리스트의 형태로 DataFrame에 저장
def filter_sequences(sequences, max_words):
    return [[idx for idx in seq if idx < max_words] for seq in sequences]


# 6) 텍스트 패딩을 생성한 후, 리스트의 형태로 DataFrame에 저장
def create_pad_sequence(df, col_nm, max_seq_len, max_words):
    ## 토큰화 및 패딩
    text_sequence = filter_sequences(tokenizer.texts_to_sequences(df[col_nm]), max_words)
    # text_sequence = tokenizer.texts_to_sequences(df[col_nm])
    padding_result = pad_sequences(text_sequence, maxlen=max_seq_len, padding='post')
    padding_result # 새로 만들어준 사전에서의 인덱스

    ## 'padded_sequences' 열을 df에 추가하고, 패딩이 적용된 시퀀스의 내용을 할당
    df[col_nm + '_padded_sequences'] = list(padding_result)

    ## 'padded_sequences' 열의 데이터 타입을 object로 변경하여 각 요소를 리스트 형태로 저장
    df[col_nm + '_padded_sequences'] = df[col_nm + '_padded_sequences'].apply(lambda x: list(x))



def merge_textrank_bart(path, which_user_item, id_col):
    # load/rename textrank
    df_textrank = pd.read_pickle(path + which_user_item+'_textrank.pkl')

    df_textrank = df_textrank.rename(columns = {
        id_col:which_user_item,
        f'{which_user_item}_summary_padded_sequences':f'{which_user_item}_embedding_textrank'})

    # load bart
    df_bart = pd.read_pickle(path + which_user_item+'_bart.pkl')

    ## prep id column
    if which_user_item+'_id' in df_bart.columns:
        df_bart = df_bart.rename(columns = {which_user_item+'_id':which_user_item})
    if id_col in df_bart.columns:
        df_bart = df_bart.rename(columns = {id_col:'item'})

    ## rename bart column
    df_bart = df_bart.rename(columns = {'bart_embedding':f'{which_user_item}_embedding_bart'})

    # merge
    df_merge = pd.merge(
        df_textrank[[which_user_item, f'{which_user_item}_embedding_textrank']],
        df_bart[[which_user_item, f'{which_user_item}_embedding_bart']],
        on = which_user_item)

    return df_merge

In [ ]:
# 리뷰 길이 0인 데이터 전처리 함수
def prep_review_length_zero(df, col):
    df_empty = df[df[col].apply(lambda x: True if clean_text(x) == True else False)]

    if df_empty.shape[0] > 0:
        print(f'리뷰 길이가d 0인 데이터 수: {df_empty.shape[0]}')

        df = df[df[col].apply(lambda x: True if clean_text(x) == False else False)]
        after_shape = df[df[col].apply(lambda x: True if clean_text(x) == True else False)].shape[0]

        print('-'*50, '리뷰 길이가 0인 데이터 전처리 완료', '-'*50)
        print(f'리뷰 길이가 0인 데이터 수: {after_shape}')
    else:
        print('리뷰 길이 0인 데이터 없음')
    return df



# 집합 데이터 분할 및 저장 함
def split_data_save(df, num, WHICH_USER_ITEM, DATA_SAVE_PATH = DATA_SAVE_PATH, CATEGORY = CATEGORY):
    df_grouped_user_split = np.array_split(df, num)

    for i in range(0, num):
        df_grouped_user_split[i].to_pickle(f'{DATA_SAVE_PATH}/{CATEGORY}_{WHICH_USER_ITEM}_split{i+1}.pkl')

    return print('----------------finished-----------------')

# Load

In [ ]:
# GloVe 불러오기 : 우선 300차원
## download glove
# urlretrieve("http://nlp.stanford.edu/data/glove.6B.zip", filename="glove.6B.zip") # SSL certificate issue when trying to download -> the certificate for the current download URL has expired
urlretrieve("https://huggingface.co/stanfordnlp/glove/resolve/main/glove.6B.zip", filename="glove.6B.zip") # Use a different URL
zf = zipfile.ZipFile('glove.6B.zip')
zf.extractall()
zf.close()

glove_dict = dict()
f = open('glove.6B.300d.txt', encoding="utf8") # 300차원의 GloVe 벡터를 사용

for line in f:
    word_vector = line.split()
    word = word_vector[0]
    word_vector_arr = np.asarray(word_vector[1:], dtype='float32') # 300개의 값을 가지는 array로 변환
    glove_dict[word] = word_vector_arr
f.close()

In [ ]:
# 전체 데이터 불러오기
df_reviews = pd.read_pickle(f"{DATA_SAVE_PATH}/{CATEGORY}_data.pkl")
df_reviews.head(5)

,review_id,review_useful,review_text,review_stars,rest_aver_stars,state,user_review_count,user_elite,user_friends,review_date,user_id,rest_id
0,KU_O5udG6zpxOg-VcAEodg,0,if you decide to eat here just be aware it is ...,3.0,3.0,PA,33,,"DS9QBM_NWJz1E279Zrao-A, XdXgIs4i5JFvtJf0rJlWsA...",2018-07-07 22:09:11,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw
2,78MWkzX8uQz0kDnhlhwAAg,2,so glad we stumbled upon this restaurant it is...,4.0,4.5,PA,33,,"DS9QBM_NWJz1E279Zrao-A, XdXgIs4i5JFvtJf0rJlWsA...",2018-10-29 21:54:59,mh_-eMZ6K5RLWhZyISBhwA,mOk3D7VczrDapNuUgLxUQw
3,krpCZHUj222Ha7AffGUZHQ,3,i was looking forward to a romantic dinner her...,2.0,4.0,PA,33,,"DS9QBM_NWJz1E279Zrao-A, XdXgIs4i5JFvtJf0rJlWsA...",2018-02-11 03:07:30,mh_-eMZ6K5RLWhZyISBhwA,L4kfcADLCU4T33i7Z0CkuA
4,NFiy4sFGVAn0A9Z22WkmZA,0,not a bad dunkin donuts but certainly not the ...,3.0,1.5,PA,33,,"DS9QBM_NWJz1E279Zrao-A, XdXgIs4i5JFvtJf0rJlWsA...",2017-03-02 22:03:57,mh_-eMZ6K5RLWhZyISBhwA,tVfJPW14AeuAHDJeleWWdQ
5,qD25Gdcd1AdfBzR3Ibx3bg,3,humptys dumplings is one of the highlights of ...,5.0,4.0,PA,33,,"DS9QBM_NWJz1E279Zrao-A, XdXgIs4i5JFvtJf0rJlWsA...",2017-01-08 20:45:48,mh_-eMZ6K5RLWhZyISBhwA,gpYBhnTk4KzvvH83TsZiQg

# GROUPBY

In [ ]:
# USER: 리뷰 집합 데이터 생성
from bs4 import BeautifulSoup

grouped_user_reviews = df_reviews[[USER_ID, REVIEW_COL]].groupby(USER_ID)[REVIEW_COL].sum()
grouped_user_reviews = pd.DataFrame(grouped_user_reviews)
grouped_user_reviews.rename(columns = {REVIEW_COL:"userReviews"}, inplace = True)
grouped_user_reviews['userReviews'] = grouped_user_reviews['userReviews'].apply(
    lambda txt: BeautifulSoup(txt, "html.parser").get_text()
)

# grouped_user_reviews['userReviews'] = grouped_user_reviews['userReviews'].apply(
#     lambda txt: re.sub(r"\.", " ", txt).replace('\n', ' ')
# )


# 인덱스를 열로 변환
grouped_user_reviews.reset_index(inplace=True)

# df 생성
group_user = pd.DataFrame({
    USER_ID: grouped_user_reviews[USER_ID].values,
    "userReviews": grouped_user_reviews["userReviews"].values})

print(group_user.shape)

(102308, 2)

In [ ]:
# ITEM: 리뷰 집합 데이터 생성
grouped_item_reviews = df_reviews[[ITEM_ID, REVIEW_COL]].groupby(ITEM_ID)[REVIEW_COL].sum()
grouped_item_reviews = pd.DataFrame(grouped_item_reviews)
grouped_item_reviews.rename(columns = {REVIEW_COL:"itemReviews"}, inplace = True)
grouped_item_reviews['itemReviews'] = grouped_item_reviews['itemReviews'].apply(
    lambda txt: BeautifulSoup(txt, "html.parser").get_text()
)

# grouped_item_reviews['itemReviews'] = grouped_item_reviews['itemReviews'].apply(
#     lambda txt: re.sub(r"\.", " ", txt).replace('\n', ' ')
# )


# 인덱스를 열로 변환
grouped_item_reviews.reset_index(inplace=True)

# df 생성
group_item = pd.DataFrame({
    ITEM_ID: grouped_item_reviews[ITEM_ID].values,
    "itemReviews": grouped_item_reviews["itemReviews"].values})

print(group_item.shape)

(19622, 2)

## Prep

In [ ]:
group_user = prep_review_length_zero(group_user, 'userReviews')
group_item = prep_review_length_zero(group_item, 'itemReviews')

In [ ]:
# review set 전처리해서 사용해서 원본 review set column 이름 변경
group_user = group_user.rename(columns = {'userReviews':'Reviews_origin'})
group_item = group_item.rename(columns = {'itemReviews':'Reviews_origin'})

# 데이터프레임을 지정된 경로에 저장
group_user.to_pickle(f'{DATA_SAVE_PATH}/{CATEGORY}_user.pkl', protocol=4)

# 데이터프레임을 지정된 경로에 저장
group_item.to_pickle(f'{DATA_SAVE_PATH}/{CATEGORY}_item.pkl', protocol=4)

In [ ]:
# 데이터프레임을 지정된 경로에서 불러오기
group_user = pd.read_pickle(f'{DATA_SAVE_PATH}/{CATEGORY}_user.pkl')
group_item = pd.read_pickle(f'{DATA_SAVE_PATH}/{CATEGORY}_item.pkl')

print(group_user.shape)
print(group_item.shape)

group_item.head(5)

In [ ]:
split_data_save(group_user, 5, 'user')
split_data_save(group_item, 5, 'item')

# Summarize

## 1)요약

1. 분할해서 요약하거나
2. 전체 유저/아이템 데이터 요약하거나

In [ ]:
# 분할 데이터 불러오기
WHICH_USER_ITEM = 'user'
WHICH_VERSION = '4'

if WHICH_VERSION == None:
  df_split = pd.read_pickle(f'{DATA_SAVE_PATH}/textrank_mid_output/{CATEGORY}_{WHICH_USER_ITEM}_{WHICH_USER_ITEM}.pkl')
else:
  df_split = pd.read_pickle(f'{DATA_SAVE_PATH}/textrank_mid_output/{CATEGORY}_{WHICH_USER_ITEM}_split{WHICH_VERSION}.pkl')

print(df_split.shape)
df_split.head(5)

(13702, 2)

,userID,Reviews_origin
41142,AGGYU65HTLHSS5E4MNE5MKJJYQFQ,interestinggreat topics discussedgreat topicgr...
41143,AGGYVACW6LCHZEHXWCIAD2VREKFA,this is one of those when i heard someone had ...
41144,AGGYZO4BMNQ4BNTNOF46XMNFVOEQ,very different but a good moviereally like thi...
41145,AGGZ6RREXQM6AFPI2DM3X4Y2ORQA,glad that amazon decided to make a series of t...
41146,AGGZAEL4ZYEWDYO2GK6FD7GUIBXA,overall a horrible movie story line acting eve...

### a.batch summarization

In [ ]:
# 배치로 요약 돌리기
lst_df = []
total = len(df_split)
batch_size = 100
ratio = 0.6

for start in tqdm(range(0, total, batch_size)):
    end = min(start + batch_size, total)
    print(f'\nfrom {start} to {end}: summarizing\n')
    _df_batch = df_split.iloc[start:end].copy()
    _df_batch['item_summary'] = _df_batch['Reviews_origin'].apply(lambda x: safe_summarize(x, ratio=ratio))
    _df_batch['item_summary'] = _df_batch['item_summary'].apply(lambda x: x.replace('.\n', '. '))
    lst_df.append(_df_batch)

  0%|          | 0/138 [00:00<?, ?it/s]

from 0 to 100: summarizing

  1%|          | 1/138 [00:01<02:23,  1.04s/it]

from 100 to 200: summarizing

  1%|▏         | 2/138 [00:01<02:09,  1.05it/s]

from 200 to 300: summarizing

  2%|▏         | 3/138 [00:02<02:15,  1.00s/it]

from 300 to 400: summarizing

  3%|▎         | 4/138 [00:03<01:58,  1.13it/s]

from 400 to 500: summarizing

  4%|▎         | 5/138 [00:05<02:26,  1.11s/it]

from 500 to 600: summarizing

  4%|▍         | 6/138 [00:12<07:11,  3.27s/it]

from 600 to 700: summarizing

  5%|▌         | 7/138 [00:13<05:14,  2.40s/it]

from 700 to 800: summarizing

  6%|▌         | 8/138 [00:13<03:59,  1.84s/it]

from 800 to 900: summarizing

  7%|▋         | 9/138 [00:14<03:04,  1.43s/it]

from 900 to 1000: summarizing

  7%|▋         | 10/138 [00:24<08:59,  4.22s/it]

from 1000 to 1100: summarizing

  8%|▊         | 11/138 [12:07<7:41:34, 218.07s/it]

from 1100 to 1200: summarizing

  9%|▊         | 12/138 [12:08<5:19:18, 152.05s/it]

from 1200 to 1300: summarizing

  9%|▉         | 13/138 [12:15<3:45:15, 108.13s/it]

from 1300 to 1400: summarizing

 10%|█         | 14/138 [12:17<2:36:45, 75.85s/it]

from 1400 to 1500: summarizing

 11%|█         | 15/138 [12:19<1:50:06, 53.71s/it]

from 1500 to 1600: summarizing

 12%|█▏        | 16/138 [12:21<1:17:27, 38.09s/it]

from 1600 to 1700: summarizing

 12%|█▏        | 17/138 [12:22<54:26, 27.00s/it]

from 1700 to 1800: summarizing

 13%|█▎        | 18/138 [12:22<37:57, 18.98s/it]

from 1800 to 1900: summarizing

 14%|█▍        | 19/138 [12:23<26:46, 13.50s/it]

from 1900 to 2000: summarizing

 14%|█▍        | 20/138 [12:26<20:05, 10.21s/it]

from 2000 to 2100: summarizing

 15%|█▌        | 21/138 [12:30<16:18,  8.36s/it]

from 2100 to 2200: summarizing

 16%|█▌        | 22/138 [12:32<12:50,  6.64s/it]

from 2200 to 2300: summarizing

 17%|█▋        | 23/138 [12:33<09:10,  4.79s/it]

from 2300 to 2400: summarizing

 17%|█▋        | 24/138 [12:33<06:39,  3.50s/it]

from 2400 to 2500: summarizing

 18%|█▊        | 25/138 [12:35<05:14,  2.78s/it]

from 2500 to 2600: summarizing

 19%|█▉        | 26/138 [12:35<04:10,  2.24s/it]

from 2600 to 2700: summarizing

 20%|█▉        | 27/138 [12:36<03:25,  1.85s/it]

from 2700 to 2800: summarizing

 20%|██        | 28/138 [12:37<02:48,  1.53s/it]

from 2800 to 2900: summarizing

 21%|██        | 29/138 [12:42<04:28,  2.47s/it]

from 2900 to 3000: summarizing

 22%|██▏       | 30/138 [12:43<03:30,  1.95s/it]

from 3000 to 3100: summarizing

 22%|██▏       | 31/138 [12:43<02:53,  1.62s/it]

from 3100 to 3200: summarizing

 23%|██▎       | 32/138 [12:46<03:28,  1.96s/it]

from 3200 to 3300: summarizing

 24%|██▍       | 33/138 [12:47<02:40,  1.53s/it]

from 3300 to 3400: summarizing

 25%|██▍       | 34/138 [12:48<02:27,  1.42s/it]

from 3400 to 3500: summarizing

 25%|██▌       | 35/138 [12:51<03:06,  1.82s/it]

from 3500 to 3600: summarizing

 26%|██▌       | 36/138 [12:51<02:35,  1.53s/it]

from 3600 to 3700: summarizing

 27%|██▋       | 37/138 [12:52<02:06,  1.25s/it]

from 3700 to 3800: summarizing

 28%|██▊       | 38/138 [12:56<03:22,  2.02s/it]

from 3800 to 3900: summarizing

 28%|██▊       | 39/138 [12:57<02:42,  1.65s/it]

from 3900 to 4000: summarizing

 29%|██▉       | 40/138 [12:58<02:44,  1.68s/it]

from 4000 to 4100: summarizing

 30%|██▉       | 41/138 [13:00<02:46,  1.71s/it]

from 4100 to 4200: summarizing

 30%|███       | 42/138 [13:02<02:48,  1.75s/it]

from 4200 to 4300: summarizing

 31%|███       | 43/138 [13:03<02:14,  1.41s/it]

from 4300 to 4400: summarizing

 32%|███▏      | 44/138 [13:04<01:57,  1.25s/it]

from 4400 to 4500: summarizing

 33%|███▎      | 45/138 [13:08<03:25,  2.21s/it]

from 4500 to 4600: summarizing

 33%|███▎      | 46/138 [13:09<02:40,  1.74s/it]

from 4600 to 4700: summarizing

 34%|███▍      | 47/138 [13:10<02:40,  1.76s/it]

from 4700 to 4800: summarizing

 35%|███▍      | 48/138 [13:12<02:20,  1.57s/it]

from 4800 to 4900: summarizing

 36%|███▌      | 49/138 [13:15<03:01,  2.04s/it]

from 4900 to 5000: summarizing

 36%|███▌      | 50/138 [13:17<03:06,  2.12s/it]

from 5000 to 5100: summarizing

 37%|███▋      | 51/138 [13:17<02:20,  1.62s/it]

from 5100 to 5200: summarizing

 38%|███▊      | 52/138 [13:22<03:29,  2.43s/it]

from 5200 to 5300: summarizing

 38%|███▊      | 53/138 [13:25<03:42,  2.62s/it]

from 5300 to 5400: summarizing

 39%|███▉      | 54/138 [14:10<21:35, 15.43s/it]

from 5400 to 5500: summarizing

 40%|███▉      | 55/138 [14:11<15:16, 11.04s/it]

from 5500 to 5600: summarizing

 41%|████      | 56/138 [14:13<11:27,  8.38s/it]

from 5600 to 5700: summarizing

 41%|████▏     | 57/138 [14:14<08:13,  6.09s/it]

from 5700 to 5800: summarizing

 42%|████▏     | 58/138 [14:14<05:48,  4.36s/it]

from 5800 to 5900: summarizing

 43%|████▎     | 59/138 [14:17<05:00,  3.81s/it]

from 5900 to 6000: summarizing

 43%|████▎     | 60/138 [14:19<04:22,  3.37s/it]

from 6000 to 6100: summarizing

 44%|████▍     | 61/138 [14:20<03:14,  2.53s/it]

from 6100 to 6200: summarizing

 45%|████▍     | 62/138 [14:21<02:34,  2.03s/it]

from 6200 to 6300: summarizing

 46%|████▌     | 63/138 [14:21<01:56,  1.56s/it]

from 6300 to 6400: summarizing

 46%|████▋     | 64/138 [14:22<01:50,  1.49s/it]

from 6400 to 6500: summarizing

 47%|████▋     | 65/138 [14:24<01:41,  1.39s/it]

from 6500 to 6600: summarizing

 48%|████▊     | 66/138 [14:25<01:45,  1.46s/it]

from 6600 to 6700: summarizing

 49%|████▊     | 67/138 [14:27<01:47,  1.51s/it]

from 6700 to 6800: summarizing

 49%|████▉     | 68/138 [14:31<02:47,  2.39s/it]

from 6800 to 6900: summarizing

 50%|█████     | 69/138 [14:33<02:29,  2.17s/it]

from 6900 to 7000: summarizing

 51%|█████     | 70/138 [14:34<02:03,  1.81s/it]

from 7000 to 7100: summarizing

 51%|█████▏    | 71/138 [14:35<01:39,  1.48s/it]

from 7100 to 7200: summarizing

 52%|█████▏    | 72/138 [14:37<01:57,  1.78s/it]

from 7200 to 7300: summarizing

 53%|█████▎    | 73/138 [14:38<01:39,  1.54s/it]

from 7300 to 7400: summarizing

 54%|█████▎    | 74/138 [14:39<01:35,  1.50s/it]

from 7400 to 7500: summarizing

 54%|█████▍    | 75/138 [15:04<08:58,  8.55s/it]

from 7500 to 7600: summarizing

 55%|█████▌    | 76/138 [15:05<06:30,  6.30s/it]

from 7600 to 7700: summarizing

 56%|█████▌    | 77/138 [15:10<05:53,  5.80s/it]

from 7700 to 7800: summarizing

 57%|█████▋    | 78/138 [15:11<04:14,  4.25s/it]

from 7800 to 7900: summarizing

 57%|█████▋    | 79/138 [15:12<03:22,  3.43s/it]

from 7900 to 8000: summarizing

 58%|█████▊    | 80/138 [15:13<02:38,  2.73s/it]

from 8000 to 8100: summarizing

 59%|█████▊    | 81/138 [16:03<16:06, 16.95s/it]

from 8100 to 8200: summarizing

 59%|█████▉    | 82/138 [16:04<11:09, 11.96s/it]

from 8200 to 8300: summarizing

 60%|██████    | 83/138 [16:31<15:15, 16.64s/it]

from 8300 to 8400: summarizing

 61%|██████    | 84/138 [16:58<17:43, 19.70s/it]

from 8400 to 8500: summarizing

 62%|██████▏   | 85/138 [16:59<12:21, 13.99s/it]

from 8500 to 8600: summarizing

 62%|██████▏   | 86/138 [17:00<08:46, 10.12s/it]

from 8600 to 8700: summarizing

 63%|██████▎   | 87/138 [17:07<07:42,  9.07s/it]

from 8700 to 8800: summarizing

 64%|██████▍   | 88/138 [17:08<05:42,  6.84s/it]

from 8800 to 8900: summarizing

 64%|██████▍   | 89/138 [17:09<03:59,  4.90s/it]

from 8900 to 9000: summarizing

 65%|██████▌   | 90/138 [17:09<02:53,  3.61s/it]

from 9000 to 9100: summarizing

 66%|██████▌   | 91/138 [17:11<02:22,  3.04s/it]

from 9100 to 9200: summarizing

 67%|██████▋   | 92/138 [17:12<01:53,  2.46s/it]

from 9200 to 9300: summarizing

 67%|██████▋   | 93/138 [17:13<01:26,  1.92s/it]

from 9300 to 9400: summarizing

 68%|██████▊   | 94/138 [17:15<01:28,  2.01s/it]

from 9400 to 9500: summarizing

 69%|██████▉   | 95/138 [17:16<01:15,  1.76s/it]

from 9500 to 9600: summarizing

 70%|██████▉   | 96/138 [17:19<01:28,  2.10s/it]

from 9600 to 9700: summarizing

 70%|███████   | 97/138 [17:22<01:39,  2.43s/it]

from 9700 to 9800: summarizing

 71%|███████   | 98/138 [17:23<01:21,  2.03s/it]

from 9800 to 9900: summarizing

 72%|███████▏  | 99/138 [17:26<01:28,  2.27s/it]

from 9900 to 10000: summarizing

 72%|███████▏  | 100/138 [17:52<06:00,  9.49s/it]

from 10000 to 10100: summarizing

 73%|███████▎  | 101/138 [17:54<04:21,  7.07s/it]

from 10100 to 10200: summarizing

 74%|███████▍  | 102/138 [17:56<03:21,  5.60s/it]

from 10200 to 10300: summarizing

 75%|███████▍  | 103/138 [17:58<02:37,  4.51s/it]

from 10300 to 10400: summarizing

 75%|███████▌  | 104/138 [18:02<02:25,  4.28s/it]

from 10400 to 10500: summarizing

 76%|███████▌  | 105/138 [18:04<02:06,  3.83s/it]

from 10500 to 10600: summarizing

 77%|███████▋  | 106/138 [18:05<01:35,  2.99s/it]

from 10600 to 10700: summarizing

 78%|███████▊  | 107/138 [18:07<01:17,  2.49s/it]

from 10700 to 10800: summarizing

 78%|███████▊  | 108/138 [18:07<00:55,  1.86s/it]

from 10800 to 10900: summarizing

 79%|███████▉  | 109/138 [18:08<00:45,  1.56s/it]

from 10900 to 11000: summarizing

 80%|███████▉  | 110/138 [18:16<01:34,  3.38s/it]

from 11000 to 11100: summarizing

 80%|████████  | 111/138 [18:28<02:40,  5.94s/it]

from 11100 to 11200: summarizing

 81%|████████  | 112/138 [18:29<01:57,  4.51s/it]

from 11200 to 11300: summarizing

 82%|████████▏ | 113/138 [18:29<01:24,  3.37s/it]

from 11300 to 11400: summarizing

 83%|████████▎ | 114/138 [18:31<01:05,  2.72s/it]

from 11400 to 11500: summarizing

 83%|████████▎ | 115/138 [18:32<00:54,  2.35s/it]

from 11500 to 11600: summarizing

 84%|████████▍ | 116/138 [18:33<00:40,  1.85s/it]

from 11600 to 11700: summarizing

 85%|████████▍ | 117/138 [18:34<00:33,  1.57s/it]

from 11700 to 11800: summarizing

 86%|████████▌ | 118/138 [18:34<00:26,  1.31s/it]

from 11800 to 11900: summarizing

 86%|████████▌ | 119/138 [18:38<00:35,  1.85s/it]

from 11900 to 12000: summarizing

 87%|████████▋ | 120/138 [18:38<00:27,  1.53s/it]

from 12000 to 12100: summarizing

 88%|████████▊ | 121/138 [18:39<00:22,  1.34s/it]

from 12100 to 12200: summarizing

 88%|████████▊ | 122/138 [20:34<09:27, 35.48s/it]

from 12200 to 12300: summarizing

 89%|████████▉ | 123/138 [20:38<06:30, 26.06s/it]

from 12300 to 12400: summarizing

 90%|████████▉ | 124/138 [20:39<04:18, 18.43s/it]

from 12400 to 12500: summarizing

 91%|█████████ | 125/138 [21:04<04:26, 20.47s/it]

from 12500 to 12600: summarizing

 91%|█████████▏| 126/138 [21:06<02:57, 14.78s/it]

from 12600 to 12700: summarizing

 92%|█████████▏| 127/138 [21:09<02:03, 11.27s/it]

from 12700 to 12800: summarizing

 93%|█████████▎| 128/138 [21:10<01:20,  8.09s/it]

from 12800 to 12900: summarizing

 93%|█████████▎| 129/138 [21:13<00:59,  6.58s/it]

from 12900 to 13000: summarizing

 94%|█████████▍| 130/138 [21:13<00:38,  4.80s/it]

from 13000 to 13100: summarizing

 95%|█████████▍| 131/138 [21:15<00:26,  3.76s/it]

from 13100 to 13200: summarizing

 96%|█████████▌| 132/138 [21:15<00:17,  2.85s/it]

from 13200 to 13300: summarizing

 96%|█████████▋| 133/138 [21:21<00:18,  3.69s/it]

from 13300 to 13400: summarizing

 97%|█████████▋| 134/138 [21:25<00:14,  3.69s/it]

from 13400 to 13500: summarizing

 98%|█████████▊| 135/138 [21:26<00:08,  2.95s/it]

from 13500 to 13600: summarizing

 99%|█████████▊| 136/138 [21:30<00:06,  3.22s/it]

from 13600 to 13700: summarizing

100%|██████████| 138/138 [21:30<00:00,  9.35s/it]

from 13700 to 13702: summarizing

In [ ]:
df_split = pd.concat(lst_df, ignore_index=True)

# 분할한 요약 데이터 저장
if WHICH_VERSION == None:
  _path = f'{DATA_SAVE_PATH}/textrank_mid_output/{CATEGORY}_{WHICH_USER_ITEM}_textrank.pkl'
else:
  _path = f'{DATA_SAVE_PATH}/textrank_mid_output/{CATEGORY}_{WHICH_USER_ITEM}_textrank{WHICH_VERSION}.pkl'

df_split.to_pickle(_path)
df_split = pd.read_pickle(_path)
df_split.head(10)

,userID,Reviews_origin,user_summary
0,AGGYU65HTLHSS5E4MNE5MKJJYQFQ,interestinggreat topics discussedgreat topicgr...,interestinggreat topics discussedgreat topicgr...
1,AGGYVACW6LCHZEHXWCIAD2VREKFA,this is one of those when i heard someone had ...,this is one of those when i heard someone had ...
2,AGGYZO4BMNQ4BNTNOF46XMNFVOEQ,very different but a good moviereally like thi...,very different but a good moviereally like thi...
3,AGGZ6RREXQM6AFPI2DM3X4Y2ORQA,glad that amazon decided to make a series of t...,glad that amazon decided to make a series of t...
4,AGGZAEL4ZYEWDYO2GK6FD7GUIBXA,overall a horrible movie story line acting eve...,overall a horrible movie story line acting eve...
5,AGGZEDMFZOFZA6VZM6OW3DTP72XA,cast perfection great movie songs and message....,cast perfection great movie songs and message....
6,AGGZFRDT32KS6CA5HT5FCZQBV5JQ,yes the acting had some rough cheesy spots and...,yes the acting had some rough cheesy spots and...
7,AGGZHAJMU7STUQ7SZDIJEPMHGKVA,great romantic story based on a real life stor...,great romantic story based on a real life stor...
8,AGGZHEPPW6SSRPQ57EUBDO46OMBA,amazing show star based solely on that. there...,there are slim special features. thats it.off ...
9,AGGZIJ7VSESHC4DG7T7F4D4YTXIQ,i cant believe this film was nominated for ac...,i cant believe this film was nominated for ac...

#### 👀debugging
아이템 데이터를 분할해서 요약하는데, 특정 분할 데이터에서 자꾸 세션이 다운되거나 뻑남\
-> 리뷰 길이를 단어 기준으로 계산해서 뻑이난 지점(=item_data32에서 70~80번째 사이에서 남)에서 리뷰 길이 확인함
(대조군: 전체 아이템 리뷰 데이터의 단어 기준 리뷰 길이)

In [ ]:
# 전체 아이템 데이터의 리뷰 길이(단어 기준)
group_item = pd.read_pickle(f'{DATA_SAVE_PATH}/{CATEGORY}_item.pkl')
group_item = group_item.rename(columns = {'itemReviews':'Reviews_origin'})
sorted_list1 = sorted(list(group_item['Reviews_origin'].apply(lambda x: len(x.split(' '))).unique()), reverse=True)
print(sorted_list1[:30])

[317878, 245546, 232253, 212843, 206482, 198460, 189288, 186930, 166917, 165418, 158072, 157204, 146586, 141663, 140428, 137724, 133981, 131070, 128240, 128116, 128014, 127115, 124616, 120125, 117282, 116831, 116306, 115028, 114681, 113151]

In [ ]:
# 해당 데이터의 리뷰 길이(단어 기준)
sorted_list = sorted(list(df_split['Reviews_origin'].apply(lambda x: len(x.split(' '))).unique()), reverse=True)
print(sorted_list[:30])

[317878, 212843, 165418, 128240, 124616, 120125, 104893, 96450, 85470, 82966, 81659, 81470, 73239, 70291, 63084, 62787, 59054, 58638, 58180, 57695, 54776, 54690, 52042, 51112, 49124, 48122, 46893, 45961, 44890, 43868]

In [ ]:
# 해당 데이터 중 세션 다운되는 구간의 리뷰 길이 확인
df_split.iloc[70:80]['Reviews_origin'].apply(lambda x: len(x.split(' ')))

4535      1623
4536      3881
4537     10216
4538       897
4539      1627
4540      5090
4541      9277
4542    317878
4543       954
4544       560
Name: Reviews_origin, dtype: int64

---------

### b.total summarization

In [ ]:
# Textrank로 요약하기
df_split = summarize_Textrank(df_split)

print(df_split.shape)
df_split.head(5)

## 2)분할 데이터 병합
- 분할해서 요약했을 때 하나로 합치기

In [ ]:
df_summary = pd.DataFrame()
LAST_SUMMARY_NUM = 5
WHICH_USER_ITEM = 'item'

for i in range(1, LAST_SUMMARY_NUM+1):
    _df_temp = pd.read_pickle(f'{DATA_SAVE_PATH}/textrank_mid_output/{CATEGORY}_{WHICH_USER_ITEM}_textrank{i}.pkl')
    df_summary = pd.concat([df_summary, _df_temp])

# user/item 리뷰 요약 집합 저장
df_summary.to_pickle(f'{DATA_SAVE_PATH}/{CATEGORY}_{WHICH_USER_ITEM}_textrank.pkl')

In [ ]:
# user/item 리뷰 요약 집합 불러오기
df_summary = pd.read_pickle(f'{DATA_SAVE_PATH}/{CATEGORY}_{WHICH_USER_ITEM}_textrank.pkl')
print(f'{WHICH_USER_ITEM}:', df_summary.shape)
df_summary.head(5)

item: (46281, 3)

,itemID,Reviews_origin,item_summary
0,0767802470,what a hell it must have been to crew one of t...,great characters and excellent storyline will ...
1,0767802497,i this is a action movie of sorts if u dont li...,i this is a action movie of sorts if u dont li...
2,0767802519,i liked it because the actually story was real...,i liked it because the actually story was real...
3,0767802535,one of the best movies ever made...about two i...,one of the best movies ever made...about two i...
4,0767803434,great moviea fiction that could be written tod...,subterfuge at its finest.awesome jobi dont und...

# Embedding - Glove

## 1)User

In [ ]:
df_user_summary = pd.read_pickle(f'{DATA_SAVE_PATH}/{CATEGORY}_user_textrank.pkl')
df_user_summary.head(3)

,userID,Reviews_origin,user_summary,user_summary_padded_sequences
0,AE223CNRS5AQOKRWCFPRBUNJ5T2Q,entertaininglove the animationfunnyentertainin...,entertaininglove the animationfunnyentertainin...,"[26910, 1, 235, 23, 821, 1, 34, 626, 13914, 49..."
1,AE22FB6A4Z54ZUJZMX2QGRWSNIZA,this show is so fresh i honestly feel from the...,this show is so fresh i honestly feel from the...,"[9927, 4, 1144, 1133, 210, 14, 71, 8933, 595, ..."
2,AE22HYC5EJJ4AUZ55HTCJFPKJFHQ,got my money back right away. so no big deal....,got my money back right away. the language and...,"[870, 11, 352, 9, 28, 150, 7, 3319, 1732, 6252..."

In [ ]:
# 단어 인덱스 맵 생성 및 임베딩 행렬 준비
## 토크나이저 초기화 및 학습
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df_user_summary['user_summary'])

max_words = 50000
word_index = tokenizer.word_index
total_words = min(max_words, len(word_index))
print(f'total_words: {total_words}')

total_words: 50000

In [ ]:
## 단어 인덱스 맵 생성 및 임베딩 행렬 준비: embedding dimension=300
user_embedding_matrix = np.zeros((total_words + 1, 300))

## 새로 만든 사전에 맞게 임베딩 해줘야함
for word, i in word_index.items():
    if i >= max_words:
        continue
    if word in glove_dict:
        user_embedding_matrix[i] = glove_dict[word]

print(user_embedding_matrix)
user_embedding_matrix.shape

[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.04656     0.21318001 -0.0074364  ...  0.0090611  -0.20988999
   0.053913  ]
 [ 0.038466   -0.039792    0.082747   ... -0.33427     0.011807
   0.059703  ]
 ...
 [ 0.0053435   0.36649001  0.38389    ... -0.35992    -0.1323
  -0.53593999]
 [ 0.01577     0.56884003  0.41288999 ...  0.040484   -0.03643
  -0.36094999]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]]

(50001, 300)

In [ ]:
create_pad_sequence(df_user_summary, 'user_summary', max_seq_len = mean_seq_length, max_words=total_words)
df_summary.head(10)

,userID,Reviews_origin,user_summary,user_summary_padded_sequences
0,AE223CNRS5AQOKRWCFPRBUNJ5T2Q,entertaininglove the animationfunnyentertainin...,entertaininglove the animationfunnyentertainin...,"[26910, 1, 235, 23, 821, 1, 34, 626, 13914, 49..."
1,AE22FB6A4Z54ZUJZMX2QGRWSNIZA,this show is so fresh i honestly feel from the...,this show is so fresh i honestly feel from the...,"[9927, 4, 1144, 1133, 210, 14, 71, 8933, 595, ..."
2,AE22HYC5EJJ4AUZ55HTCJFPKJFHQ,got my money back right away. so no big deal....,got my money back right away. the language and...,"[870, 11, 352, 9, 28, 150, 7, 3319, 1732, 6252..."
3,AE22IEG7RTLEV5TXRK5DCOKFZJLQ,doubting there is any accuracy to this drama i...,doubting there is any accuracy to this drama i...,"[141, 121, 5, 1, 6, 272, 198, 7, 58, 4, 331, 4..."
4,AE22KH6ZLWIZPZ3UM5SFMUKZ7UAA,i started to watch lore and loved it season w...,i started to watch lore and loved it season w...,"[168, 8, 922, 2, 686, 19, 4, 280, 83, 185, 19,..."
5,AE22KUGFMITQ24E7J7QVZEYAW7CA,for such a consistently great director this fi...,for such a consistently great director this fi...,"[9, 19, 71, 229, 4, 280, 703, 191, 1, 204, 189..."
6,AE22PFS2QZMV5EPBL7Y6TLMVRLJQ,this is a great series. sensitive fastpaced ...,this is a great series. the setting in montrea...,"[7, 3778, 1205, 337, 882, 1, 213, 4, 123, 1454..."
7,AE22QDEN6KCC2YYSJWUIT6ARADFQ,good movie has depth.while the fee for rentin...,good movie has depth.while the fee for rentin...,"[5, 1, 100, 55, 1337, 112, 109, 20, 226, 140, ..."
8,AE22QSIR4YRJG5V5NHOL7KDAN3ZQ,well thought out sentences might be too much f...,well thought out sentences might be too much f...,"[3, 76, 105, 210, 102, 436, 219, 148, 11, 6168..."
9,AE22RGXR4645FMVQZJUYIOM5NTMQ,cant wait this k set. im glad v and vi are om...,loved seeing bale in another comic book movie....,"[1064, 21, 1, 385, 443, 29, 35, 1, 330, 64, 10..."

In [ ]:
np.max(list(df_summary['user_summary_padded_sequences'].values))

49996

In [ ]:
# save as npy
np.save(f'{DATA_SAVE_PATH}/{CATEGORY}_user_glove_dic.npy', user_embedding_matrix)

# user 리뷰 요약 시퀀스 저장
df_user_summary.to_pickle(f'{DATA_SAVE_PATH}/{CATEGORY}_user_textrank.pkl')

In [ ]:
# 저장한 데이터 확인
df_user_textrank = pd.read_pickle(f'{DATA_SAVE_PATH}/{CATEGORY}_user_textrank.pkl')

print(np.max(list(df_user_textrank['user_summary_padded_sequences'].values)))
df_user_textrank.head(5)

49996

,userID,Reviews_origin,user_summary,user_summary_padded_sequences
0,AE223CNRS5AQOKRWCFPRBUNJ5T2Q,entertaininglove the animationfunnyentertainin...,entertaininglove the animationfunnyentertainin...,"[26910, 1, 235, 23, 821, 1, 34, 626, 13914, 49..."
1,AE22FB6A4Z54ZUJZMX2QGRWSNIZA,this show is so fresh i honestly feel from the...,this show is so fresh i honestly feel from the...,"[9927, 4, 1144, 1133, 210, 14, 71, 8933, 595, ..."
2,AE22HYC5EJJ4AUZ55HTCJFPKJFHQ,got my money back right away. so no big deal....,got my money back right away. the language and...,"[870, 11, 352, 9, 28, 150, 7, 3319, 1732, 6252..."
3,AE22IEG7RTLEV5TXRK5DCOKFZJLQ,doubting there is any accuracy to this drama i...,doubting there is any accuracy to this drama i...,"[141, 121, 5, 1, 6, 272, 198, 7, 58, 4, 331, 4..."
4,AE22KH6ZLWIZPZ3UM5SFMUKZ7UAA,i started to watch lore and loved it season w...,i started to watch lore and loved it season w...,"[168, 8, 922, 2, 686, 19, 4, 280, 83, 185, 19,..."

## 2)Item

In [ ]:
df_item_summary = pd.read_pickle(f'{DATA_SAVE_PATH}/{CATEGORY}_item_textrank.pkl')
df_item_summary.head(3)

,itemID,Reviews_origin,item_summary
0,0767802470,what a hell it must have been to crew one of t...,great characters and excellent storyline will ...
1,0767802497,i this is a action movie of sorts if u dont li...,i this is a action movie of sorts if u dont li...
2,0767802519,i liked it because the actually story was real...,i liked it because the actually story was real...

In [ ]:
# 2. Item review
## 토크나이저 초기화 및 학습
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df_item_summary['item_summary'])

max_words = 50000
word_index = tokenizer.word_index
total_words = min(max_words, len(word_index))
print(f'total_words: {total_words}')

total_words: 50000

In [ ]:
## 단어 인덱스 맵 생성 및 임베딩 행렬 준비: embedding dimension=300
item_embedding_matrix = np.zeros((total_words + 1, 300))

## 새로 만든 사전에 맞게 임베딩 해줘야함
for word, i in word_index.items():
    if i >= max_words:
        continue
    if word in glove_dict:
        item_embedding_matrix[i] = glove_dict[word]

print(item_embedding_matrix)
item_embedding_matrix.shape

[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.04656     0.21318001 -0.0074364  ...  0.0090611  -0.20988999
   0.053913  ]
 [ 0.038466   -0.039792    0.082747   ... -0.33427     0.011807
   0.059703  ]
 ...
 [-0.59227002 -0.69761997  0.14       ...  0.56614    -0.39524999
   0.15745001]
 [ 0.12574001  0.37318     0.17019001 ... -0.53294998  0.043552
  -0.32440001]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]]

(50001, 300)

In [ ]:
## max_sequ_len = 데이터별 평균 시퀀스 길이로 두고 embedding 생성
create_pad_sequence(df_item_summary, 'item_summary', max_seq_len = mean_seq_length, max_words=total_words)
df_item_summary.head(10)

,itemID,Reviews_origin,item_summary,item_summary_padded_sequences
0,0767802470,what a hell it must have been to crew one of t...,great characters and excellent storyline will ...,"[57, 5, 21013, 51, 19797, 1036, 11759, 2, 5263..."
1,0767802497,i this is a action movie of sorts if u dont li...,i this is a action movie of sorts if u dont li...,"[10, 9, 1487, 65, 18, 62, 18, 79, 31, 493, 2, ..."
2,0767802519,i liked it because the actually story was real...,i liked it because the actually story was real...,"[51, 61, 134, 2, 106, 397, 147, 1, 2822, 5, 20..."
3,0767802535,one of the best movies ever made...about two i...,one of the best movies ever made...about two i...,"[378, 5, 2140, 2338, 8, 671, 66, 1, 12, 1888, ..."
4,0767803434,great moviea fiction that could be written tod...,subterfuge at its finest.awesome jobi dont und...,"[41, 7, 12, 21, 1588, 2, 302, 9, 21, 192, 42, ..."
5,076780421X,greatdefinitely worth gettingit was a good mov...,greatdefinitely worth gettingit was a good mov...,"[655, 10, 173, 24, 67, 26138, 42, 7, 295, 1, 1..."
6,0767805763,greatloved itbizarre. but good acting. love v...,love voighti love this movie its one of the be...,"[42, 7, 12, 29, 30, 5, 1, 107, 2339, 6104, 53,..."
7,0767806239,good moviethis is a movie that is timeless a m...,good moviethis is a movie that is timeless a m...,"[22, 969, 8, 3, 12, 14, 8, 2424, 3, 12, 14, 24..."
8,076780676X,it was fun to watch. mostly predictable. somet...,it was fun to watch. something that is safe fo...,"[3, 2408, 1907, 44, 17268, 133, 192, 954, 24, ..."
9,0767806808,funny moviereally funny movie in my opinion. i...,funny moviereally funny movie in my opinion. i...,"[15, 1, 116, 198, 6, 244, 7, 12, 120, 2185, 1,..."

In [ ]:
np.max(list(df_item_summary['item_summary_padded_sequences'].values))

49997

In [ ]:
# save as npy
np.save(f'{DATA_SAVE_PATH}/{CATEGORY}_item_glove_dic.npy', item_embedding_matrix)

# item 리뷰 요약 시퀀스 저장
df_item_summary.to_pickle(f'{DATA_SAVE_PATH}/{CATEGORY}_item_textrank.pkl')

In [ ]:
# 저장한 데이터 확인
df_item_textrank = pd.read_pickle(f'{DATA_SAVE_PATH}/{CATEGORY}_item_textrank.pkl')

print(np.max(list(df_item_textrank['item_summary_padded_sequences'].values)))
df_item_summary.head(5)

49997

,itemID,Reviews_origin,item_summary,item_summary_padded_sequences
0,0767802470,what a hell it must have been to crew one of t...,great characters and excellent storyline will ...,"[57, 5, 21013, 51, 19797, 1036, 11759, 2, 5263..."
1,0767802497,i this is a action movie of sorts if u dont li...,i this is a action movie of sorts if u dont li...,"[10, 9, 1487, 65, 18, 62, 18, 79, 31, 493, 2, ..."
2,0767802519,i liked it because the actually story was real...,i liked it because the actually story was real...,"[51, 61, 134, 2, 106, 397, 147, 1, 2822, 5, 20..."
3,0767802535,one of the best movies ever made...about two i...,one of the best movies ever made...about two i...,"[378, 5, 2140, 2338, 8, 671, 66, 1, 12, 1888, ..."
4,0767803434,great moviea fiction that could be written tod...,subterfuge at its finest.awesome jobi dont und...,"[41, 7, 12, 21, 1588, 2, 302, 9, 21, 192, 42, ..."

# Merge

In [ ]:
df_user_tr_bart = merge_textrank_bart(
    path = f"{DATA_SAVE_PATH}/{CATEGORY}_", which_user_item = 'user', id_col = USER_ID)
df_user_tr_bart.head(5)

,user,user_embedding_textrank,user_embedding_bart
0,AE223CNRS5AQOKRWCFPRBUNJ5T2Q,"[26910, 1, 235, 23, 821, 1, 34, 626, 13914, 49...","[-0.024359785, -0.8241518, 0.030495215, -1.543..."
1,AE22FB6A4Z54ZUJZMX2QGRWSNIZA,"[9927, 4, 1144, 1133, 210, 14, 71, 8933, 595, ...","[0.48813066, 0.3011386, 2.4315197, -3.2398725,..."
2,AE22HYC5EJJ4AUZ55HTCJFPKJFHQ,"[870, 11, 352, 9, 28, 150, 7, 3319, 1732, 6252...","[0.55364466, -0.7212269, -0.8160649, -1.709610..."
3,AE22IEG7RTLEV5TXRK5DCOKFZJLQ,"[141, 121, 5, 1, 6, 272, 198, 7, 58, 4, 331, 4...","[0.08958933, 0.31884375, -1.5628182, -2.429583..."
4,AE22KH6ZLWIZPZ3UM5SFMUKZ7UAA,"[168, 8, 922, 2, 686, 19, 4, 280, 83, 185, 19,...","[-0.40517938, 0.15798128, -0.23898572, -0.7440..."

In [ ]:
df_item_tr_bart = merge_textrank_bart(
    path = f"{DATA_SAVE_PATH}/{CATEGORY}_", which_user_item = 'item', id_col = ITEM_ID)
df_item_tr_bart.head(5)

,item,item_embedding_textrank,item_embedding_bart
0,0767802470,"[57, 5, 21013, 51, 19797, 1036, 11759, 2, 5263...","[-0.45721912, 0.22749305, 0.76964325, -0.61435..."
1,0767802497,"[10, 9, 1487, 65, 18, 62, 18, 79, 31, 493, 2, ...","[0.31335288, 0.03406208, 0.58331335, -2.655624..."
2,0767802519,"[51, 61, 134, 2, 106, 397, 147, 1, 2822, 5, 20...","[-0.5766005, -0.5311635, 1.1096023, -2.885747,..."
3,0767802535,"[378, 5, 2140, 2338, 8, 671, 66, 1, 12, 1888, ...","[-0.28083846, -0.22997823, -0.5919732, -2.8058..."
4,0767803434,"[41, 7, 12, 21, 1588, 2, 302, 9, 21, 192, 42, ...","[-0.55130845, -0.5349555, 0.3148671, -2.708737..."

# Mapping

In [ ]:
# load rating, userID, itemID
df_all = pd.read_pickle(f'{DATA_SAVE_PATH}/{CATEGORY}_data.pkl')
df_all = df_all.rename(columns = {USER_ID:'user', ITEM_ID:'item', RATING_COL:'rating'})
df_all.head(5)

,rating,item,user,reviewtext,date,year
0,1.0,B08X6JFYT9,AFGNIWCBLQT2QIXXKIW7Q6VREZRQ,so for all of those who think by buying the cu...,2021-03-01 15:57:45.651000064,2021
1,5.0,B07PND31HD,AFGNIWCBLQT2QIXXKIW7Q6VREZRQ,i wish there were more delightful movies like ...,2020-10-22 17:18:42.180999936,2020
2,1.0,B08DX1WFWK,AFGNIWCBLQT2QIXXKIW7Q6VREZRQ,spoilers this was just so ridiculous. so we ge...,2020-10-14 06:42:45.477999872,2020
3,5.0,B005LTHT72,AFGNIWCBLQT2QIXXKIW7Q6VREZRQ,i dont think there is a movie that makes me la...,2020-10-11 05:55:28.479000064,2020
4,2.0,B07R6YJMW5,AFGNIWCBLQT2QIXXKIW7Q6VREZRQ,i wanted to like this movie but the acting was...,2020-10-06 00:44:30.933000192,2020

In [ ]:
# merge user/item data
df_final_output = pd.merge(df_all[['user', 'item', 'rating']].copy(), df_user_tr_bart, on = 'user')
df_final_output = pd.merge(df_final_output, df_item_tr_bart, on = 'item')

df_final_output.head(5)

,user,item,rating,user_embedding_textrank,user_embedding_bart,item_embedding_textrank,item_embedding_bart
0,AFGNIWCBLQT2QIXXKIW7Q6VREZRQ,B08X6JFYT9,1.0,"[1, 34, 8, 14, 19, 160, 423, 104, 123, 19, 160...","[0.93794405, -0.08286553, -0.043052204, -3.257...","[27, 35, 24, 71, 8, 431, 202, 65, 4, 31, 30, 3...","[-0.16816601, -0.38978252, 0.44575274, -3.7842..."
1,AFKHQSGVE53BKPT4DQFJGRFMCLWQ,B08X6JFYT9,5.0,"[81, 26747, 31221, 3226, 1013, 2, 15479, 579, ...","[0.20747374, -0.6719453, 0.25165808, -3.481782...","[27, 35, 24, 71, 8, 431, 202, 65, 4, 31, 30, 3...","[-0.16816601, -0.38978252, 0.44575274, -3.7842..."
2,AH4HCQLXK72IFJESRHIP5MOGJG4Q,B08X6JFYT9,1.0,"[75, 2861, 580, 6, 2019, 8, 697, 64, 609, 53, ...","[-1.2395746, 1.521351, 1.3411634, -1.8987955, ...","[27, 35, 24, 71, 8, 431, 202, 65, 4, 31, 30, 3...","[-0.16816601, -0.38978252, 0.44575274, -3.7842..."
3,AEK3GBHW4JC2YMMVNDMUIXTONH6Q,B08X6JFYT9,5.0,"[7, 76, 155, 20, 408, 65, 231, 44, 9, 6, 35, 1...","[-0.18107454, -0.7605884, -1.2539482, -1.11232...","[27, 35, 24, 71, 8, 431, 202, 65, 4, 31, 30, 3...","[-0.16816601, -0.38978252, 0.44575274, -3.7842..."
4,AHRPCIOV6TWLFMNASTQLLTKBUIEQ,B08X6JFYT9,1.0,"[3919, 27, 1, 47, 10, 10, 6, 92, 24, 1, 674, 5...","[0.66322744, 0.3501363, 0.8260165, -1.8900322,...","[27, 35, 24, 71, 8, 431, 202, 65, 4, 31, 30, 3...","[-0.16816601, -0.38978252, 0.44575274, -3.7842..."

# Save File

In [ ]:
# textrank 시퀀스 생성 후 저장
df_final_output.to_pickle(f'{DATA_SAVE_PATH}/{CATEGORY}_raw_embedding.pkl')
df_final_output = pd.read_pickle(f'{DATA_SAVE_PATH}/{CATEGORY}_raw_embedding.pkl')

print(np.max(list(df_final_output['user_embedding_textrank'].values)))
print(np.max(list(df_final_output['item_embedding_textrank'].values)))
print(df_final_output.shape)
df_final_output.head(3)

49996
49997
(731248, 7)

,user,item,rating,user_embedding_textrank,user_embedding_bart,item_embedding_textrank,item_embedding_bart
0,AFGNIWCBLQT2QIXXKIW7Q6VREZRQ,B08X6JFYT9,1.0,"[1, 34, 8, 14, 19, 160, 423, 104, 123, 19, 160...","[0.93794405, -0.08286553, -0.043052204, -3.257...","[27, 35, 24, 71, 8, 431, 202, 65, 4, 31, 30, 3...","[-0.16816601, -0.38978252, 0.44575274, -3.7842..."
1,AFKHQSGVE53BKPT4DQFJGRFMCLWQ,B08X6JFYT9,5.0,"[81, 26747, 31221, 3226, 1013, 2, 15479, 579, ...","[0.20747374, -0.6719453, 0.25165808, -3.481782...","[27, 35, 24, 71, 8, 431, 202, 65, 4, 31, 30, 3...","[-0.16816601, -0.38978252, 0.44575274, -3.7842..."
2,AH4HCQLXK72IFJESRHIP5MOGJG4Q,B08X6JFYT9,1.0,"[75, 2861, 580, 6, 2019, 8, 697, 64, 609, 53, ...","[-1.2395746, 1.521351, 1.3411634, -1.8987955, ...","[27, 35, 24, 71, 8, 431, 202, 65, 4, 31, 30, 3...","[-0.16816601, -0.38978252, 0.44575274, -3.7842..."